name: release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.meta.outputs.date }}
    steps:
      - name: Prepare release meta
        id: meta
        run: |
          echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

  release-bin:
    name: Release Go Binary
    runs-on: ubuntu-latest
    needs:
      - meta
    strategy:
      matrix:
        goos: [ windows, linux ]
        goarch: [ "386", amd64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.35
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.19.5
          project_path: cmd/unlockproxy
          ldflags: "-X 'main.buildTime=${{ needs.meta.outputs.date }}' -X 'main.buildCommit=${{ github.sha }}' -X 'main.buildVersion=${{ github.ref_name }}'"
          sha256sum: true
